#pragma once

#define V2D_BUTTON(X)       (1 << ((X)-1))
#define V2D_BUTTON_LEFT     1
#define V2D_BUTTON_MIDDLE   2
#define V2D_BUTTON_RIGHT    3
#define V2D_BUTTON_X1       4
#define V2D_BUTTON_X2       5
#define V2D_BUTTON_LMASK    V2D_BUTTON(V2D_BUTTON_LEFT)
#define V2D_BUTTON_MMASK    V2D_BUTTON(V2D_BUTTON_MIDDLE)
#define V2D_BUTTON_RMASK    V2D_BUTTON(V2D_BUTTON_RIGHT)
#define V2D_BUTTON_X1MASK   V2D_BUTTON(V2D_BUTTON_X1)
#define V2D_BUTTON_X2MASK   V2D_BUTTON(V2D_BUTTON_X2)

namespace visions2D {
	typedef enum {
		MOUSECODE_LEFT = V2D_BUTTON_LEFT,
		MOUSECODE_MIDDLE = V2D_BUTTON_MIDDLE,
		MOUSECODE_RIGHT = V2D_BUTTON_RIGHT
	} v2D_Mousecode;
}